Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Gerdemann.ReCAPTCHA:ReCAPTCHA':
            implementationClassName: Gerdemann\ReCAPTCHA\FormElements\ReCAPTCHAFormElement
            superTypes:
              'Neos.Form:FormElement': true
            renderingOptions:
              templatePathPattern: 'resource://Gerdemann.ReCAPTCHA/Private/Form/ReCAPTCHA.html'
        validatorPresets:
          'Gerdemann.ReCAPTCHA:ReCAPTCHA':
            implementationClassName: Gerdemann\ReCAPTCHA\Validation\ReCAPTCHAValidator
  Neos:
    fusion:
      autoInclude:
        Gerdemann.ReCAPTCHA: true

Gerdemann:
  ReCAPTCHA:
    sitekey: ~
    secret: ~
